# Generated by Django 4.2 on 2025-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
